---
- name: Creating the apache
  package:
    name: "{{ web_package }}"
    state: latest
    
- name: Edit servername
  lineinfile:
    path: "{{ web_path }}"
    regexp: "^ServerName"
    inserafter: "#ServerName"
    line: "ServerName {{ansible_fqdn}}:80"
    
- name: Permissions
  file:
    path: '/var/www/html'
    mode: '3750'
    owner: root
    group: "{{ web_group }}"

- name: Create index
  copy:
    content: "Welcome {{ansible_fqdn}}"
    dest: '/var/www/html/index.html'
    mode: 640
    group: "{{ web_group }}"
    
- name: firewall for centos
  systemd:
    name: firewalld
    state: started
    enabled: true
  when: ansible_distribution == 'CentOS'
  
- name: open centos firewall port
  firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled
  when: ansible_distribution == 'CentOS'
    
- name: firewall for ubuntu
  systemd:
    name: ufw
    state: started
    enabled: true
  when: ansible_distribution == 'Ubuntu'
  
- name: open ubuntu firewall ports
  ufw: 
    port: "{{ item }}"
    rule: allow
    state: enabled
  when: ansible_distribution == 'Ubuntu' 
  loop:
    - ssh
    - http

- name: initialize apache
  systemd:
    name: "{{ web_package }}"
    state: started
    enabled: true
